import type { Metadata } from "next";
import "./globals.css";
import { NextAuthProvider } from "./components/NextAuthProvider";
import { Providers } from "./providers";
import { fonts } from "./styles/fonts";
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
} ) {
  return (
    <ClerkProvider>
      <html lang="en" className={fonts.dmSans.className}>
        <body>
          <Providers>
              {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
