import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';


//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
} ) {
  return (
    <SessionProvider>


    <html lang="en">
      <body>{children}</body>
    </html>

    </SessionProvider>
  );
}
